name: In Your Best Light
favicon: null
layout_spectrum: 0.49842
typography_spectrum: 0.2065603882074356
title: In Your Best Light
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030303'
    - '#858585'
    - '#2f2f2f'
    - '#c0c0c0'
  brandStrength: 0.9375
  lightness: 0.28360756929032505
  saturation: 0.40496832970529795
  rhythmicContrast: 0.6557770245708525
purpose: []
